function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    isdefined(Base, Symbol("##any#596")) && precompile(Tuple{getfield(Base, Symbol("##any#596")),Function,typeof(any),Function,Array{Expr,1}})
    isdefined(Base, Symbol("##printstyled#709")) && precompile(Tuple{getfield(Base, Symbol("##printstyled#709")),Bool,Symbol,typeof(printstyled),String,Vararg{String,N} where N})
    isdefined(Base, Symbol("#387#388")) && precompile(Tuple{getfield(Base, Symbol("#387#388")),IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},SubArray{Float64,2,Array{Float64,3},Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Int64},false}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,3}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,4}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,5}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,6}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Int64}},typeof(dropdims),Array{Float64,7}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64,Int64}}},typeof(dropdims),Array{Float64,5}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(dropdims),Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(dropdims),Array{Float64,4}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(dropdims),Array{Float64,5}})
    precompile(Tuple{Core.kwftype(typeof(Base.dropdims)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(dropdims),Array{Float64,6}})
    precompile(Tuple{Core.kwftype(typeof(Base.eachslice)),NamedTuple{(:dims,),Tuple{Int64}},typeof(eachslice),PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}}})
    precompile(Tuple{Core.kwftype(typeof(Base.mapslices)),NamedTuple{(:dims,),Tuple{Int64}},typeof(mapslices),Function,Array{Int64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.maximum)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(maximum),Array{Float64,4}})
    precompile(Tuple{Core.kwftype(typeof(Base.printstyled)),NamedTuple{(:bold, :color),Tuple{Bool,Symbol}},typeof(printstyled),Base.TTY,String,Vararg{String,N} where N})
    precompile(Tuple{Core.kwftype(typeof(Base.printstyled)),NamedTuple{(:bold, :color),Tuple{Bool,Symbol}},typeof(printstyled),String,String,Vararg{String,N} where N})
    precompile(Tuple{Core.kwftype(typeof(Base.prod)),NamedTuple{(:dims,),Tuple{Int64}},typeof(prod),Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.prod)),NamedTuple{(:dims,),Tuple{Int64}},typeof(prod),PermutedDimsArray{Float64,4,(1, 2, 4, 3),(1, 2, 4, 3),Array{Float64,4}}})
    precompile(Tuple{Core.kwftype(typeof(Base.reverse)),NamedTuple{(:dims,),Tuple{Int64}},typeof(reverse),Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.reverse)),NamedTuple{(:dims,),Tuple{Int64}},typeof(reverse),Array{Int64,4}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Float64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Float64,3}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Float64,5}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Float64,6}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Float64,7}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),Array{Int64,2}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),PermutedDimsArray{Float64,3,(3, 1, 2),(2, 3, 1),SubArray{Float64,3,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Int64}},typeof(sum),PermutedDimsArray{Float64,4,(3, 2, 1, 4),(3, 2, 1, 4),SubArray{Float64,4,Array{Float64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64,Int64}}},typeof(sum),Array{Float64,5}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(sum),Array{Float64,6}})
    precompile(Tuple{Core.kwftype(typeof(Base.sum)),NamedTuple{(:dims,),Tuple{Tuple{Int64,Int64}}},typeof(sum),PermutedDimsArray{Float64,4,(3, 1, 4, 2),(2, 4, 1, 3),Array{Float64,4}}})
    precompile(Tuple{Core.kwftype(typeof(Base.with_output_color)),NamedTuple{(:bold,),Tuple{Bool}},typeof(Base.with_output_color),Function,Symbol,Base.TTY,String,Vararg{String,N} where N})
    precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Axes,F,Args} where Args<:Tuple where F where Axes},typeof(-),Tuple{Int64,Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}})
    precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{6},Axes,F,Args} where Args<:Tuple where F where Axes},typeof(*),Tuple{Array{Float64,6},Array{Float64,6}}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}}},Array{Float64,3}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Base.ReshapedArray{Float64,3,PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}},Base.ReshapedArray{Float64,3,PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(2, 1, 3),(2, 1, 3),Array{Float64,3}}},Array{Float64,3}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(2, 3, 1),(3, 1, 2),Array{Float64,3}}},Array{Float64,3}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(3, 1, 2),(2, 3, 1),Array{Float64,3}}},Array{Float64,3}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(3, 1, 2),(2, 3, 1),SubArray{Float64,3,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}}},SubArray{Float64,3,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}}},Array{Float64,3}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(1, 2, 4, 3),(1, 2, 4, 3),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(1, 3, 4, 2),(1, 4, 2, 3),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(1, 4, 2, 3),(1, 3, 4, 2),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(2, 1, 3, 4),(2, 1, 3, 4),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(2, 1, 4, 3),(2, 1, 4, 3),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(2, 4, 3, 1),(4, 1, 3, 2),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(3, 1, 2, 4),(2, 3, 1, 4),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(3, 1, 4, 2),(2, 4, 1, 3),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(3, 2, 1, 4),(3, 2, 1, 4),SubArray{Float64,4,Array{Float64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}}},SubArray{Float64,4,Array{Float64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(3, 2, 4, 1),(4, 2, 1, 3),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(3, 4, 1, 2),(3, 4, 1, 2),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,4,(4, 2, 3, 1),(4, 2, 3, 1),Array{Float64,4}}},Array{Float64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(1, 2, 4, 3, 5),(1, 2, 4, 3, 5),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(2, 4, 5, 1, 3),(4, 1, 5, 2, 3),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(3, 4, 2, 5, 1),(5, 3, 1, 2, 4),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(3, 4, 5, 1, 2),(4, 5, 1, 2, 3),Base.ReshapedArray{Float64,5,PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}},NTuple{4,Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}},Base.ReshapedArray{Float64,5,PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}},NTuple{4,Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(4, 1, 2, 5, 3),(2, 3, 5, 1, 4),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(4, 2, 3, 5, 1),(5, 2, 3, 1, 4),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,5,(5, 1, 4, 2, 3),(2, 4, 5, 3, 1),Array{Float64,5}}},Array{Float64,5}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,6,(2, 3, 5, 6, 1, 4),(5, 1, 2, 6, 3, 4),Array{Float64,6}}},Array{Float64,6}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,6,(3, 1, 5, 4, 2, 6),(2, 5, 1, 4, 3, 6),Array{Float64,6}}},Array{Float64,6}})
    precompile(Tuple{Type{PermutedDimsArray{Float64,6,(4, 2, 6, 3, 1, 5),(5, 2, 4, 1, 6, 3),Array{Float64,6}}},Array{Float64,6}})
    precompile(Tuple{Type{PermutedDimsArray{Int64,3,(2, 3, 1),(3, 1, 2),SubArray{Int64,3,Array{Int64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}}},SubArray{Int64,3,Array{Int64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}})
    precompile(Tuple{Type{PermutedDimsArray{Int64,3,(2, 3, 1),(3, 1, 2),SubArray{Int64,3,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}}},SubArray{Int64,3,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}})
    precompile(Tuple{Type{PermutedDimsArray{Int64,4,(2, 4, 1, 3),(3, 1, 4, 2),Array{Int64,4}}},Array{Int64,4}})
    precompile(Tuple{Type{PermutedDimsArray{Int64,4,(2, 4, 1, 3),(3, 1, 4, 2),SubArray{Int64,4,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}}},SubArray{Int64,4,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}})
    precompile(Tuple{Type{PermutedDimsArray},Array{Float64,3},Tuple{Int64,Int64,Int64}})
    precompile(Tuple{Type{PermutedDimsArray},Array{Float64,4},NTuple{4,Int64}})
    precompile(Tuple{Type{PermutedDimsArray},Array{Float64,5},NTuple{5,Int64}})
    precompile(Tuple{Type{PermutedDimsArray},Array{Float64,6},NTuple{6,Int64}})
    precompile(Tuple{Type{Tuple},Array{Function,1}})
    precompile(Tuple{typeof(==),Array{Base.ReshapedArray{Float64,4,SubArray{Float64,3,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64},true},Tuple{}},1},Array{Array{Float64,4},1}})
    precompile(Tuple{typeof(==),Array{Complex{Float64},2},Array{Complex{Float64},2}})
    precompile(Tuple{typeof(==),Array{Float64,1},Array{Float64,1}})
    precompile(Tuple{typeof(==),Array{Int64,1},SubArray{Int64,1,Array{Int64,2},Tuple{Int64,Array{Int64,1}},false}})
    precompile(Tuple{typeof(==),Array{Int64,2},SubArray{Int64,2,Array{Int64,2},Tuple{Array{Int64,1},Array{Int64,1}},false}})
    precompile(Tuple{typeof(==),Array{Int64,2},SubArray{Int64,2,Array{Int64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Array{Int64,1}},false}})
    precompile(Tuple{typeof(==),SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true},Array{Float64,1}})
    precompile(Tuple{typeof(==),SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Array{Float64,1}})
    precompile(Tuple{typeof(==),SubArray{Float64,2,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},StepRange{Int64,Int64}},false},Array{Float64,2}})
    precompile(Tuple{typeof(==),SubArray{Float64,2,Array{Float64,4},Tuple{Int64,Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false},Array{Float64,2}})
    precompile(Tuple{typeof(==),SubArray{Int64,2,Array{Int64,2},Tuple{Base.Slice{Base.OneTo{Int64}},UnitRange{Int64}},true},Array{Int64,2}})
    precompile(Tuple{typeof(==),SubArray{Int64,4,Array{Int64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}}},false},Array{Int64,4}})
    precompile(Tuple{typeof(Base.Broadcast.__dot__),Expr})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Base.Broadcast.DefaultArrayStyle{1},Function,Array{Array{Float64,4},1},Base.RefValue{Colon},Base.RefValue{Colon},Vararg{Any,N} where N})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,Array{Array{Float64,3},2},Function,Function,Int64})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,Array{Array{Float64,4},1},Function,Function,Int64,Vararg{Any,N} where N})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,Function,Array{Float64,1},Val{3}})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,Function,Array{Int64,3},Val{2}})
    precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,PermutedDimsArray{Int64,3,(2, 3, 1),(3, 1, 2),SubArray{Int64,3,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}},Int64})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Array{Float64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(-),Tuple{Array{Float64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(/),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Float64,Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(exp),Tuple{Array{Float64,1}}}}},Int64}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,3},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(identity),Tuple{Array{Float64,3}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,3},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,3},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,3,(2, 1, 3),(2, 1, 3),Array{Float64,3}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,3},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,3,(3, 1, 2),(2, 3, 1),Array{Float64,3}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,4},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,4,(3, 4, 1, 2),(3, 4, 1, 2),Array{Float64,4}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Float64,5},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{5},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,5,(3, 4, 5, 1, 2),(4, 5, 1, 2, 3),Base.ReshapedArray{Float64,5,PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}},NTuple{4,Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Int64,4},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{PermutedDimsArray{Int64,4,(2, 4, 1, 3),(3, 1, 4, 2),SubArray{Int64,4,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Array{Int64,4},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(identity),Tuple{SubArray{Int64,4,Array{Int64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}}},false}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),Base.ReshapedArray{Float64,4,PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(identity),Tuple{PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(-),Tuple{SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),SubArray{Int64,1,Array{Int64,1},Tuple{StepRange{Int64,Int64}},true},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Int64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Int64,Array{Int64,1}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize!),SubArray{Int64,1,Array{Int64,1},Tuple{StepRange{Int64,Int64}},true},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{SubArray{Int64,1,Array{Int64,1},Tuple{StepRange{Int64,Int64}},true},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Int64,SubArray{Int64,1,Array{Int64,1},Tuple{StepRange{Int64,Int64}},true}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,Type{CartesianIndex},Tuple{Array{Int64,1},Array{Int64,1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(!),Tuple{Array{Bool,1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Array{Float64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(log),Tuple{Array{Float64,1}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Int64,Array{Float64,1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(*),Tuple{Int64,Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Float64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(-),Tuple{Int64,Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(/),Tuple{Array{Float64,1},Float64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(==),Tuple{Array{Float64,1},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(==),Tuple{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Array{Float64,1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(copy),Tuple{Array{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(getproperty),Tuple{Array{NamedTuple{(:scal, :vect),Tuple{Int64,Array{Int64,1}}},1},Base.RefValue{Symbol}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(identity),Tuple{Array{SubArray{Int64,1,Array{Int64,2},Tuple{Int64,UnitRange{Int64}},true},1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(sum),Tuple{Array{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},1}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(view),Tuple{Array{Array{Float64,4},1},Base.RefValue{Colon},Base.RefValue{Colon},Int64,Base.RefValue{Colon}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(*),Tuple{Array{Float64,2},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(sqrt),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Array{Float64,1},Int64}}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(+),Tuple{Array{Float64,2},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(*),Tuple{Complex{Bool},Array{Float64,2}}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(+),Tuple{Array{Int64,2},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(/),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(log),Tuple{Array{Float64,2}}},Float64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(==),Tuple{SubArray{Float64,2,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Int64},true},Array{Float64,2}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(sqrt),Tuple{Array{Float64,2}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{2},Nothing,typeof(view),Tuple{Array{Array{Float64,3},2},Base.RefValue{Colon},Base.RefValue{Colon},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(*),Tuple{Array{Float64,3},Array{Float64,3}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(*),Tuple{Array{Int64,2},Array{Float64,3}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{Array{Int64,3},Array{Int64,3},Array{Float64,2}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(Base.literal_pow),Tuple{Base.RefValue{typeof(^)},Array{Int64,3},Base.RefValue{Val{2}}}},Array{Int64,3}}},Array{Float64,2}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{Base.ReshapedArray{Int64,3,UnitRange{Int64},Tuple{}},Complex{Bool}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{PermutedDimsArray{Int64,3,(2, 3, 1),(3, 1, 2),SubArray{Int64,3,Array{Int64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(+),Tuple{PermutedDimsArray{Int64,3,(2, 3, 1),(3, 1, 2),SubArray{Int64,3,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{3},Nothing,typeof(==),Tuple{Array{Float64,3},Array{Float64,3}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,Type{Int64},Tuple{PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(*),Tuple{Array{Float64,2},Array{Float64,3},Array{Float64,4}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(*),Tuple{Array{Float64,3},Array{Float64,4}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{Array{Float64,4},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{PermutedDimsArray{Float64,4,(2, 1, 3, 4),(2, 1, 3, 4),Array{Float64,4}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{PermutedDimsArray{Float64,4,(2, 1, 4, 3),(2, 1, 4, 3),Array{Float64,4}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{PermutedDimsArray{Int64,4,(2, 4, 1, 3),(3, 1, 4, 2),Array{Int64,4}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(+),Tuple{PermutedDimsArray{Int64,4,(2, 4, 1, 3),(3, 1, 4, 2),SubArray{Int64,4,Array{Int64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}},Int64}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{4},Nothing,typeof(==),Tuple{Array{Float64,4},Array{Float64,4}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{5},Nothing,typeof(*),Tuple{Array{Float64,3},Array{Float64,5}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{5},Nothing,typeof(*),Tuple{Array{Float64,5},Array{Float64,5}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{5},Nothing,typeof(+),Tuple{Int64,PermutedDimsArray{Float64,5,(3, 4, 2, 5, 1),(5, 3, 1, 2, 4),Array{Float64,5}}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{6},Nothing,typeof(*),Tuple{Array{Float64,6},Array{Float64,6}}}})
    precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{7},Nothing,typeof(*),Tuple{Array{Float64,7},Array{Float64,7}}}})
    precompile(Tuple{typeof(Base.PermutedDimsArrays._permutedims!),PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}},PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}},CartesianIndices{1,Tuple{Base.OneTo{Int64}}},CartesianIndices{0,Tuple{}},CartesianIndices{0,Tuple{}},Int64,Int64})
    precompile(Tuple{typeof(Base._getindex),IndexLinear,Array{Float64,4},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Vararg{Union{Real, AbstractArray},N} where N})
    precompile(Tuple{typeof(Base._mapreduce_dim),Function,Function,NamedTuple{(),Tuple{}},Array{Float64,4},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(Base._mapreduce_dim),Function,Function,NamedTuple{(),Tuple{}},Array{Float64,5},Tuple{Int64,Int64,Int64}})
    precompile(Tuple{typeof(Base._mapreduce_dim),Function,Function,NamedTuple{(),Tuple{}},Array{Float64,6},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(Base._mapreduce_dim),Function,Function,NamedTuple{(),Tuple{}},PermutedDimsArray{Float64,4,(1, 2, 4, 3),(1, 2, 4, 3),Array{Float64,4}},Int64})
    precompile(Tuple{typeof(Base._mapreduce_dim),Function,Function,NamedTuple{(),Tuple{}},PermutedDimsArray{Float64,4,(3, 1, 4, 2),(2, 4, 1, 3),Array{Float64,4}},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(Base._unsafe_getindex),IndexLinear,Array{Float64,4},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}})
    precompile(Tuple{typeof(Base.concatenate_setindex!),Array{Float64,2},Array{Float64,1},Base.OneTo{Int64},Vararg{Any,N} where N})
    precompile(Tuple{typeof(Base.mapreducedim!),Function,Function,Array{Float64,4},Array{Float64,4}})
    precompile(Tuple{typeof(Base.mapreducedim!),Function,Function,Array{Float64,5},Array{Float64,5}})
    precompile(Tuple{typeof(Base.mapreducedim!),Function,Function,Array{Float64,6},Array{Float64,6}})
    precompile(Tuple{typeof(Base.reducedim_init),Function,typeof(max),Array{Float64,4},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(Base.setindex_widen_up_to),Array{Nothing,1},Bool,Int64})
    precompile(Tuple{typeof(Base.setindex_widen_up_to),Array{Nothing,1},Expr,Int64})
    precompile(Tuple{typeof(Base.setindex_widen_up_to),Array{Nothing,1},QuoteNode,Int64})
    precompile(Tuple{typeof(Base.show_unquoted),Base.GenericIOBuffer{Array{UInt8,1}},Tuple{Colon,Colon,typeof(*)},Int64,Int64})
    precompile(Tuple{typeof(Base.show_unquoted),IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Array{Float64,2},Int64,Int64})
    precompile(Tuple{typeof(Base.show_unquoted),IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Array{Float64,3},Int64,Int64})
    precompile(Tuple{typeof(collect),Base.Generator{Array{Any,1},Type{QuoteNode}}})
    precompile(Tuple{typeof(collect),Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}})
    precompile(Tuple{typeof(collect),PermutedDimsArray{Float64,4,(3, 4, 1, 2),(3, 4, 1, 2),Array{Float64,4}}})
    precompile(Tuple{typeof(copy),Base.Broadcast.Broadcasted{Base.Broadcast.Style{Tuple},Nothing,typeof(something),Tuple{Tuple{String,String,Symbol,String,Expr,String,String},Base.RefValue{String}}}})
    precompile(Tuple{typeof(getindex),Array{Any,1},Array{Bool,1}})
    precompile(Tuple{typeof(getindex),Array{Any,1},BitArray{1}})
    precompile(Tuple{typeof(getindex),Array{Float64,3},Function,Function,Int64})
    precompile(Tuple{typeof(getindex),Array{Float64,4},Function,Function,Int64,Function})
    precompile(Tuple{typeof(getindex),Array{Int64,2},Array{CartesianIndex{2},1}})
    precompile(Tuple{typeof(getindex),Array{Int64,2},Array{Int64,1},Array{Int64,1}})
    precompile(Tuple{typeof(getindex),Array{Int64,2},Function,BitArray{1}})
    precompile(Tuple{typeof(getindex),Array{Int64,2},Int64,Array{Int64,1}})
    precompile(Tuple{typeof(getindex),PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Base.ReshapedArray{Float64,3,PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}},Int64,Int64,Int64})
    precompile(Tuple{typeof(getindex),PermutedDimsArray{Float64,5,(4, 1, 2, 5, 3),(2, 3, 5, 1, 4),Array{Float64,5}},Int64,Int64,Int64,Int64,Int64})
    precompile(Tuple{typeof(merge),NamedTuple{(:flat, :outsize, :reversed, :shuffled),NTuple{4,Array{Any,1}}},NamedTuple{(:name, :outer, :inner, :innerflat, :static, :left, :right),Tuple{Symbol,Array{Any,1},Array{Any,1},Array{Any,1},Bool,Symbol,Expr}}})
    precompile(Tuple{typeof(merge),NamedTuple{(:flat, :outsize, :reversed, :shuffled, :name, :outer, :inner, :innerflat, :static, :left, :right),Tuple{Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Symbol,Array{Any,1},Array{Any,1},Array{Any,1},Bool,Expr,Expr}},NamedTuple{(:redfun, :reduced, :rdims, :right),Tuple{Expr,Array{Any,1},Array{Int64,1},Expr}}})
    precompile(Tuple{typeof(merge),NamedTuple{(:flat, :outsize, :reversed, :shuffled, :name, :outer, :inner, :innerflat, :static, :left, :right),Tuple{Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Symbol,Array{Any,1},Array{Any,1},Array{Any,1},Bool,Expr,Expr}},NamedTuple{(:redfun, :reduced, :rdims, :right),Tuple{Symbol,Array{Any,1},Array{Int64,1},Expr}}})
    precompile(Tuple{typeof(merge),NamedTuple{(:flat, :outsize, :reversed, :shuffled, :name, :outer, :inner, :innerflat, :static, :left, :right),Tuple{Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Symbol,Array{Any,1},Array{Any,1},Array{Any,1},Bool,Symbol,Expr}},NamedTuple{(:redfun, :reduced, :rdims, :right),Tuple{Symbol,Array{Any,1},Array{Int64,1},Expr}}})
    precompile(Tuple{typeof(permutedims),Array{Float64,2},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(permutedims),Array{Float64,3},Tuple{Int64,Int64,Int64}})
    precompile(Tuple{typeof(permutedims),Array{Float64,4},NTuple{4,Int64}})
    precompile(Tuple{typeof(permutedims),Array{Float64,5},NTuple{5,Int64}})
    precompile(Tuple{typeof(permutedims),Array{Float64,6},NTuple{6,Int64}})
    precompile(Tuple{typeof(permutedims),Array{Int64,3},Tuple{Int64,Int64,Int64}})
    precompile(Tuple{typeof(reshape),Array{Float64,1},Tuple{Int64,Int64,Colon}})
    precompile(Tuple{typeof(reshape),Array{Float64,2},Tuple{Int64,Colon,Int64}})
    precompile(Tuple{typeof(reshape),Array{Float64,2},Tuple{Int64,Int64,Int64,Colon,Int64,Int64}})
    precompile(Tuple{typeof(reshape),Array{Float64,4},Tuple{Int64,Int64,Int64,Colon,Int64}})
    precompile(Tuple{typeof(reshape),Array{Float64,5},Tuple{Int64,Int64,Colon,Int64}})
    precompile(Tuple{typeof(reshape),Base.ReshapedArray{Float64,2,PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}},Tuple{Int64,Int64,Colon}})
    precompile(Tuple{typeof(reshape),Base.ReshapedArray{Float64,2,PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}},NTuple{4,Int64}})
    precompile(Tuple{typeof(reshape),Base.ReshapedArray{Float64,3,PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}},NTuple{4,Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}},Tuple{Colon,Int64,Int64,Int64,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,3,(1, 3, 2),(1, 3, 2),Array{Float64,3}},Tuple{Colon}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,3,(3, 2, 1),(3, 2, 1),Array{Float64,3}},Tuple{Colon,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,4,(1, 3, 2, 4),(1, 3, 2, 4),Array{Float64,4}},Tuple{Int64,Colon}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,4,(1, 3, 4, 2),(1, 4, 2, 3),Array{Float64,4}},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,5,(1, 2, 4, 3, 5),(1, 2, 4, 3, 5),Array{Float64,5}},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,5,(4, 5, 1, 2, 3),(3, 4, 5, 1, 2),Array{Float64,5}},Tuple{Colon,Int64,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,6,(3, 1, 5, 4, 2, 6),(2, 5, 1, 4, 3, 6),Array{Float64,6}},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(reshape),PermutedDimsArray{Float64,6,(4, 2, 6, 3, 1, 5),(5, 2, 4, 1, 6, 3),Array{Float64,6}},Tuple{Int64,Int64}})
    precompile(Tuple{typeof(similar),Array{Float64,1},Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}})
    precompile(Tuple{typeof(sin),Int64})
    precompile(Tuple{typeof(sum!),Array{Float64,0},Array{Float64,2}})
    precompile(Tuple{typeof(sum!),Array{Float64,1},Array{Float64,2}})
    precompile(Tuple{typeof(sum!),Array{Float64,2},PermutedDimsArray{Float64,3,(3, 1, 2),(2, 3, 1),SubArray{Float64,3,Array{Float64,4},Tuple{Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Int64,Base.Slice{Base.OneTo{Int64}}},false}}})
    precompile(Tuple{typeof(sum!),Array{Float64,2},PermutedDimsArray{Float64,4,(3, 1, 2, 4),(2, 3, 1, 4),Array{Float64,4}}})
    precompile(Tuple{typeof(sum!),Array{Float64,3},PermutedDimsArray{Float64,4,(3, 2, 1, 4),(3, 2, 1, 4),SubArray{Float64,4,Array{Float64,4},Tuple{StepRange{Int64,Int64},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}},Base.Slice{Base.OneTo{Int64}}},false}}})
    precompile(Tuple{typeof(sum!),Array{Float64,4},PermutedDimsArray{Float64,6,(2, 3, 5, 6, 1, 4),(5, 1, 2, 6, 3, 4),Array{Float64,6}}})
    precompile(Tuple{typeof(sum!),SubArray{Int64,1,Array{Int64,1},Tuple{StepRange{Int64,Int64}},true},Array{Int64,2}})
    precompile(Tuple{typeof(tan),Int64})
    precompile(Tuple{typeof(view),Array{Float64,2},Function,Int64})
    precompile(Tuple{typeof(view),Array{Float64,4},Int64,Function,Int64,Function})
    precompile(Tuple{typeof(view),Array{Int64,2},Function,BitArray{1}})
    precompile(Tuple{typeof(view),Array{Int64,2},Function,UnitRange{Int64}})
    precompile(Tuple{typeof(view),Array{Int64,2},Int64,Function})
    precompile(Tuple{typeof(view),Array{Int64,4},Function,Function,Int64,Function})
    precompile(Tuple{typeof(view),SubArray{Int64,1,Array{Int64,2},Tuple{Int64,Base.Slice{Base.OneTo{Int64}}},true},Array{Int64,1}})

    precompile(Tuple{typeof(!=),Array{Int64,1},UnitRange{Int64}})
    precompile(Tuple{typeof(Base._unique!),typeof(identity),Array{Any,1},Set{Symbol},Int64,Int64})
    precompile(Tuple{typeof(Base.setindex_widen_up_to),Array{Symbol,1},Nothing,Int64})
    precompile(Tuple{typeof(in),Symbol,Array{Any,1}})
    precompile(Tuple{typeof(merge),NamedTuple{(:flat, :outsize, :reversed, :shuffled),NTuple{4,Array{Any,1}}},NamedTuple{(:name, :outer, :inner, :innerflat, :static, :left, :right),Tuple{Symbol,Array{Any,1},Array{Any,1},Array{Any,1},Bool,Expr,Expr}}})
end
